export const projectsBatches = [
  {
    project: "B05 - Farm",
    "project number": "B05",
    "project name": "Farm",
    "project manager": "Marcelo Ortega",
    "project status": "Active",
    "project type": "LOC",
    "start date": "01-apr-2023",
    linkables: [{ name: `/dashboard/items/batches/B05/` }],
    "batch info": [
      {
        num: 1,
        name: "Living Room",
        type: "furniture",
      },
      {
        num: 2,
        name: "Decorative Objects",
        type: "decor",
      },
      {
        num: 3,
        name: "Decorative Lighting",
        type: "decor",
      },
      {
        num: 4,
        name: "Artwork",
        type: "decor",
      },
      {
        num: 5,
        name: "Floor Coverings",
        type: "decor",
      },
    ],

    batches: [
      {
        linkables: [
          {
            "item ref": "/dashboard/items/batches/B05/Living-Room/",
          },
        ],
        "Living Room": [
          {
            image: "/sofa.jpg",
            location: "101-00-01-00",
            price: "1200e",
            size: "36x40",
            ordered: "23-Apr-2023",
            description: "Sectional Sofa",
            "item ref": "LR10",
            qty: 2,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "28",
            "part no.": "FO302",
            supplier: "COLEFAX",
            manufacturer: "COLEFAX",
            uom: "LM",
            coO: "United Kingdom",
            "del address": "Sofa Chair and Co",
            "supplier address": "406 Chelsea Harbour",
            "fabric res": "FB123-789",
            "fabric date": "27-07-3023",
            "sample inspection": "NO",
            "shop drawing": "NO",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-01-01",
            price: "800e",
            size: "24x25",
            ordered: "12-May-2023",
            description: "Armchair",
            "item ref": "LR21",
            qty: 1,
            "Budget Cur": "USD",
            "Budget Rate": 850,
            "Act Cur": "EUR",
            "Act Rate": 750,
            batch: "29",
            "part no.": "AC601",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB456-123",
            "fabric date": "15-06-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-01-02",
            price: "500e",
            size: "30x30",
            ordered: "05-Jun-2023",
            description: "Coffee Table",
            "item ref": "LR32",
            qty: 1,
            "Budget Cur": "EUR",
            "Budget Rate": 900,
            "Act Cur": "GBP",
            "Act Rate": 800,
            batch: "30",
            "part no.": "CT102",
            supplier: "Home Goods",
            manufacturer: "Home Goods",
            uom: "EA",
            coO: "Germany",
            "del address": "Furniture Warehouse",
            "supplier address": "789 Oak Avenue",
            "fabric res": "FB789-456",
            "fabric date": "20-07-2023",
            "sample inspection": "NO",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-01-03",
            price: "950e",
            size: "18x22",
            ordered: "18-Jul-2023",
            description: "Dining Chair",
            "item ref": "LR43",
            qty: 4,
            "Budget Cur": "GBP",
            "Budget Rate": 750,
            "Act Cur": "USD",
            "Act Rate": 850,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
        ],
      },
      {
        linkables: [
          {
            "item ref": "/dashboard/items/batches/B05/Decorative-Objects/",
          },
        ],
        "Decorative Objects": [
          {
            image: "/sofa.jpg",
            location: "101-00-02-00",
            price: "60e",
            size: "8x8",
            ordered: "05-Jul-2023",
            description: "Ceramic Vase",
            "item ref": "DO10",
            Qty: 5,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-02-01",
            price: "80e",
            size: "10x10",
            ordered: "20-Jul-2023",
            description: "Decorative Tray",
            "item ref": "DO21",
            Qty: 2,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-02-02",
            price: "40e",
            size: "6x6",
            ordered: "01-Aug-2023",
            description: "Candle Holder",
            "item ref": "DO32",
            Qty: 3,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-02-03",
            price: "100e",
            size: "12x12",
            ordered: "10-Aug-2023",
            description: "Sculpture",
            "item ref": "DO43",
            Qty: 1,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
        ],
      },
      {
        linkables: [
          {
            "item ref": "/dashboard/items/batches/B05/Decorative-Lighting/",
          },
        ],
        "Decorative Lighting": [
          {
            image: "/sofa.jpg",
            location: "101-00-03-00",
            price: "180e",
            size: "18x18",
            ordered: "05-Jul-2023",
            description: "Pendant Light",
            "item ref": "DL10",
            Qty: 2,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-03-01",
            price: "120e",
            size: "14x14",
            ordered: "15-Jul-2023",
            description: "Table Lamp",
            "item ref": "DL21",
            Qty: 5,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-03-02",
            price: "250e",
            size: "22x22",
            ordered: "30-Jul-2023",
            description: "Floor Lamp",
            "item ref": "DL32",
            Qty: 1,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-03-03",
            price: "150e",
            size: "16x16",
            ordered: "10-Aug-2023",
            description: "Wall Sconce",
            "item ref": "DL43",
            Qty: 3,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
        ],
      },
      {
        linkables: [
          {
            "item ref": "/dashboard/items/batches/B05/Artwork/",
          },
        ],
        Artwork: [
          {
            image: "/sofa.jpg",
            location: "101-00-04-00",
            price: "650e",
            size: "24x36",
            ordered: "10-Jul-2023",
            description: "Abstract Painting",
            "item ref": "AW10",
            Qty: 1,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-04-01",
            price: "300e",
            size: "18x24",
            ordered: "25-Jul-2023",
            description: "Photographic Print",
            "item ref": "AW21",
            Qty: 2,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-04-02",
            price: "500e",
            size: "30x30",
            ordered: "08-Aug-2023",
            description: "Sculpture",
            "item ref": "AW32",
            Qty: 1,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
          {
            image: "/sofa.jpg",
            location: "101-00-04-03",
            price: "400e",
            size: "20x20",
            ordered: "18-Aug-2023",
            description: "Canvas Print",
            "item ref": "AW43",
            Qty: 3,
            "Budget Cur": "SAR",
            "Budget Rate": 10250,
            "Act Cur": "GBP",
            "Act Rate": 2500,
            batch: "31",
            "part no.": "DC201",
            supplier: "Furniture Co.",
            manufacturer: "Furniture Co.",
            uom: "EA",
            coO: "United States",
            "del address": "Home Furnishings",
            "supplier address": "123 Main Street",
            "fabric res": "FB987-654",
            "fabric date": "10-08-2023",
            "sample inspection": "YES",
            "shop drawing": "YES",
          },
        ],
      },
    ],
  },
  {
    project: "MUD - Elevated Seating",
    "project number": "MUD",
    "project name": "Elevating Seating",
    "project manager": "Marcelo Ortega",
    "project status": "Active",
    "project type": "LOC",
    "start date": "20-Oct-2022",
    linkables: [{ name: `/dashboard/items/batches/MUD/` }],
    "batch info": [
      {
        num: 1,
        name: "Furniture",
        type: "furniture",
      },
      {
        num: 2,
        name: "Decorative Accessories",
        type: "decor",
      },
      {
        num: 3,
        name: "Decorative lighting",
        type: "decor",
      },
      {
        num: 4,
        name: "Artwork",
        type: "decor",
      },
      {
        num: 5,
        name: "Carpet",
        type: "decor",
      },
    ],

    batches: [
      {
        Furniture: [
          {
            price: "1200e",
            size: "36x40",
            ordered: "23-Apr-2023",
            description: "Sectional Sofa",
            "item ref": "SS10",
          },
          {
            price: "800e",
            size: "24x25",
            ordered: "12-Apr-2023",
            description: "Armchair",
            "item ref": "SS21",
          },
          {
            price: "500e",
            size: "30x30",
            ordered: "15-May-2023",
            description: "Coffee Table",
            "item ref": "SS32",
          },
          {
            price: "950e",
            size: "18x22",
            ordered: "02-Jun-2023",
            description: "Dining Chair",
            "item ref": "SS43",
          },
        ],
      },
      {
        "Decorative Accessories": [
          {
            price: "60e",
            size: "8x8",
            ordered: "05-Jul-2023",
            description: "Ceramic Vase",
            "item ref": "SS10",
          },
          {
            price: "80e",
            size: "10x10",
            ordered: "20-Jul-2023",
            description: "Decorative Tray",
            "item ref": "SS21",
          },
          {
            price: "40e",
            size: "6x6",
            ordered: "01-Aug-2023",
            description: "Candle Holder",
            "item ref": "SS32",
          },
          {
            price: "100e",
            size: "12x12",
            ordered: "10-Aug-2023",
            description: "Sculpture",
            "item ref": "SS43",
          },
        ],
      },
      {
        "Decorative lighting": [
          {
            price: "180e",
            size: "18x18",
            ordered: "05-Jul-2023",
            description: "Pendant Light",
            "item ref": "SS10",
          },
          {
            price: "120e",
            size: "14x14",
            ordered: "15-Jul-2023",
            description: "Table Lamp",
            "item ref": "SS21",
          },
          {
            price: "250e",
            size: "22x22",
            ordered: "30-Jul-2023",
            description: "Floor Lamp",
            "item ref": "SS32",
          },
          {
            price: "150e",
            size: "16x16",
            ordered: "10-Aug-2023",
            description: "Wall Sconce",
            "item ref": "SS43",
          },
        ],
      },
      {
        Artwork: [
          {
            price: "650e",
            size: "24x36",
            ordered: "10-Jul-2023",
            description: "Abstract Painting",
            "item ref": "SS10",
          },
          {
            price: "400e",
            size: "18x24",
            ordered: "25-Jul-2023",
            description: "Photograph",
            "item ref": "SS21",
          },
          {
            price: "800e",
            size: "30x40",
            ordered: "05-Aug-2023",
            description: "Canvas Print",
            "item ref": "SS32",
          },
          {
            price: "1200e",
            size: "36x48",
            ordered: "20-Aug-2023",
            description: "Mixed Media",
            "item ref": "SS43",
          },
        ],
      },
      {
        Carpet: [
          {
            price: "200e",
            size: "5x8",
            ordered: "12-Jul-2023",
            description: "Area Rug",
            "item ref": "SS10",
          },
          {
            price: "350e",
            size: "8x10",
            ordered: "22-Jul-2023",
            description: "Runner Rug",
            "item ref": "SS21",
          },
          {
            price: "300e",
            size: "6x9",
            ordered: "05-Aug-2023",
            description: "Shag Carpet",
            "item ref": "SS32",
          },
          {
            price: "500e",
            size: "10x12",
            ordered: "15-Aug-2023",
            description: "Wool Rug",
            "item ref": "SS43",
          },
        ],
      },
    ],
  },
  {
    project: "HID03 - Aljazirah",
    "project number": "HID03",
    "project name": "Aljazirah",
    "project manager": "Marcelo Ortega",
    "project status": "Active",
    "project type": "LOC",
    "start date": "01-jan-2023",
    linkables: [{ name: `/dashboard/items/batches/HID03/` }],
    "batch info": [
      {
        num: 1,
        name: "Chairs",
        type: "furniture",
      },
      {
        num: 2,
        name: "Tables",
        type: "furniture",
      },
      {
        num: 3,
        name: "Lighting",
        type: "decor",
      },
      {
        num: 4,
        name: "Rugs",
        type: "decor",
      },
    ],
    batches: [
      {
        Chairs: [
          {
            price: "250e",
            size: "24x24",
            ordered: "23-Apr-2023",
            description: "Accent Chair",
            "item ref": "SS01",
          },
          {
            price: "150e",
            size: "18x20",
            ordered: "12-Apr-2023",
            description: "Dining Chair",
            "item ref": "SS02",
          },
          {
            price: "300e",
            size: "22x26",
            ordered: "15-May-2023",
            description: "Armchair",
            "item ref": "SS03",
          },
          {
            price: "200e",
            size: "20x22",
            ordered: "02-Jun-2023",
            description: "Desk Chair",
            "item ref": "SS04",
          },
        ],
      },
      {
        Tables: [
          {
            price: "500e",
            size: "48x60",
            ordered: "05-Jul-2023",
            description: "Dining Table",
            "item ref": "SS01",
          },
          {
            price: "350e",
            size: "36x40",
            ordered: "20-Jul-2023",
            description: "Coffee Table",
            "item ref": "SS02",
          },
          {
            price: "450e",
            size: "30x30",
            ordered: "01-Aug-2023",
            description: "Side Table",
            "item ref": "SS03",
          },
          {
            price: "600e",
            size: "72x36",
            ordered: "10-Aug-2023",
            description: "Console Table",
            "item ref": "SS04",
          },
        ],
      },
      {
        Lighting: [
          {
            price: "200e",
            size: "18x18",
            ordered: "05-Jul-2023",
            description: "Chandelier",
            "item ref": "SS01",
          },
          {
            price: "100e",
            size: "14x14",
            ordered: "15-Jul-2023",
            description: "Table Lamp",
            "item ref": "SS02",
          },
          {
            price: "150e",
            size: "22x22",
            ordered: "30-Jul-2023",
            description: "Floor Lamp",
            "item ref": "SS03",
          },
          {
            price: "120e",
            size: "16x16",
            ordered: "10-Aug-2023",
            description: "Wall Sconce",
            "item ref": "SS04",
          },
        ],
      },
      {
        Rugs: [
          {
            price: "300e",
            size: "5x8",
            ordered: "12-Jul-2023",
            description: "Area Rug",
            "item ref": "SS01",
          },
          {
            price: "250e",
            size: "8x10",
            ordered: "22-Jul-2023",
            description: "Runner Rug",
            "item ref": "SS02",
          },
          {
            price: "200e",
            size: "6x9",
            ordered: "05-Aug-2023",
            description: "Shag Rug",
            "item ref": "SS03",
          },
          {
            price: "350e",
            size: "10x12",
            ordered: "15-Aug-2023",
            description: "Wool Rug",
            "item ref": "SS04",
          },
        ],
      },
    ],
  },
  {
    project: "C1150 - Golf Club",
    "project number": "C1150",
    "project name": "Golf Club",
    "project manager": "Marcelo Ortega",
    "project status": "closed",
    "project type": "LOC",
    "start date": "05-may-2023",
    linkables: [{ name: `/dashboard/items/batches/C1150/` }],
    "batch info": [
      {
        num: 1,
        name: "Furniture",
        type: "furniture",
      },
      {
        num: 2,
        name: "Decorative Accessories",
        type: "decor",
      },
      {
        num: 3,
        name: "Decorative lighting",
        type: "decor",
      },
      {
        num: 4,
        name: "Artwork",
        type: "decor",
      },
      {
        num: 5,
        name: "Carpet",
        type: "decor",
      },
    ],

    batches: [
      {
        Furniture: [
          {
            "item ref": "SS11",
            price: "1500e",
            size: "48x60",
            ordered: "23-Apr-2023",
            description: "King-size Bed",
          },
          {
            "item ref": "SS22",
            price: "600e",
            size: "36x40",
            ordered: "12-Apr-2023",
            description: "Dresser",
          },
          {
            "item ref": "SS33",
            price: "800e",
            size: "24x25",
            ordered: "15-May-2023",
            description: "Accent Chair",
          },
          {
            "item ref": "SS44",
            price: "1200e",
            size: "72x36",
            ordered: "02-Jun-2023",
            description: "Dining Table",
          },
        ],
      },
      {
        "Decorative Accessories": [
          {
            "item ref": "SS11",
            price: "80e",
            size: "10x10",
            ordered: "05-Jul-2023",
            description: "Throw Pillow",
          },
          {
            "item ref": "SS22",
            price: "50e",
            size: "8x8",
            ordered: "20-Jul-2023",
            description: "Decorative Tray",
          },
          {
            "item ref": "SS33",
            price: "30e",
            size: "6x6",
            ordered: "01-Aug-2023",
            description: "Ceramic Vase",
          },
          {
            "item ref": "SS44",
            price: "100e",
            size: "12x12",
            ordered: "10-Aug-2023",
            description: "Wall Clock",
          },
        ],
      },
      {
        "Decorative lighting": [
          {
            "item ref": "SS11",
            price: "200e",
            size: "18x18",
            ordered: "05-Jul-2023",
            description: "Chandelier",
          },
          {
            "item ref": "SS22",
            price: "150e",
            size: "14x14",
            ordered: "15-Jul-2023",
            description: "Table Lamp",
          },
          {
            "item ref": "SS33",
            price: "250e",
            size: "22x22",
            ordered: "30-Jul-2023",
            description: "Floor Lamp",
          },
          {
            "item ref": "SS44",
            price: "180e",
            size: "16x16",
            ordered: "10-Aug-2023",
            description: "Wall Sconce",
          },
        ],
      },
      {
        Artwork: [
          {
            "item ref": "SS11",
            price: "900e",
            size: "30x40",
            ordered: "10-Jul-2023",
            description: "Abstract Painting",
          },
          {
            "item ref": "SS22",
            price: "500e",
            size: "18x24",
            ordered: "25-Jul-2023",
            description: "Framed Print",
          },
          {
            "item ref": "SS33",
            price: "700e",
            size: "24x36",
            ordered: "05-Aug-2023",
            description: "Canvas Art",
          },
        ],
      },
    ],
  },
  {
    project: "B07 - Hill House",
    "project number": "B07",
    "project name": "Hill House",
    "project manager": "Marcelo Ortega",
    "project status": "Active",
    "project type": "LOC",
    "start date": "01-may-2023",
    linkables: [{ name: `/dashboard/items/batches/B07` }],
    "batch info": [
      {
        num: 1,
        name: "Upholstery",
        type: "furniture",
      },
      {
        num: 2,
        name: "Decorative Accessories",
        type: "decor",
      },
      {
        num: 3,
        name: "Decorative lighting",
        type: "decor",
      },
      {
        num: 4,
        name: "Artwork",
        type: "decor",
      },
      {
        num: 5,
        name: "Carpet",
        type: "decor",
      },
    ],
    batches: [
      {
        linkables: [{ "item ref": `/dashboard/items/batches/B07/Upholstery/` }],
        Upholstery: [
          {
            price: "1500e",
            size: "48x60",
            ordered: "23-Apr-2023",
            description: "Velvet Sofa",
            "item ref": "SS11",
          },
          {
            price: "600e",
            size: "36x40",
            ordered: "12-Apr-2023",
            description: "Leather Recliner",
            "item ref": "SS22",
          },
          {
            price: "800e",
            size: "24x25",
            ordered: "15-May-2023",
            description: "Fabric Armchair",
            "item ref": "SS33",
          },
          {
            price: "1200e",
            size: "72x36",
            ordered: "02-Jun-2023",
            description: "Chaise Lounge",
            "item ref": "SS44",
          },
        ],
      },
      {
        linkables: [
          {
            "item ref": `/dashboard/items/batches/B07/Decorative-Accessories/`,
          },
        ],

        "Decorative Accessories": [
          {
            price: "80e",
            size: "10x10",
            ordered: "05-Jul-2023",
            description: "Throw Pillow",
            "item ref": "SS11",
          },
          {
            price: "50e",
            size: "8x8",
            ordered: "20-Jul-2023",
            description: "Decorative Tray",
            "item ref": "SS22",
          },
          {
            price: "30e",
            size: "6x6",
            ordered: "01-Aug-2023",
            description: "Ceramic Vase",
            "item ref": "SS33",
          },
          {
            price: "100e",
            size: "12x12",
            ordered: "10-Aug-2023",
            description: "Wall Clock",
            "item ref": "SS44",
          },
        ],
      },
      {
        linkables: [
          {
            "item ref": `/dashboard/items/batches/B07/Decorative-lighting/`,
          },
        ],
        "Decorative lighting": [
          {
            price: "200e",
            size: "18x18",
            ordered: "05-Jul-2023",
            description: "Chandelier",
            "item ref": "SS11",
          },
          {
            price: "150e",
            size: "14x14",
            ordered: "15-Jul-2023",
            description: "Table Lamp",
            "item ref": "SS22",
          },
          {
            price: "250e",
            size: "22x22",
            ordered: "30-Jul-2023",
            description: "Floor Lamp",
            "item ref": "SS33",
          },
          {
            price: "180e",
            size: "16x16",
            ordered: "10-Aug-2023",
            description: "Wall Sconce",
            "item ref": "SS44",
          },
        ],
      },
      {
        linkables: [
          {
            "item ref": `/dashboard/items/batches/B07/Artwork/`,
          },
        ],
        Artwork: [
          {
            price: "900e",
            size: "30x40",
            ordered: "10-Jul-2023",
            description: "Abstract Painting",
            "item ref": "SS11",
          },
          {
            price: "500e",
            size: "18x24",
            ordered: "25-Jul-2023",
            description: "Sculpture",
            "item ref": "SS22",
          },
          {
            price: "700e",
            size: "24x36",
            ordered: "05-Aug-2023",
            description: "Mixed Media",
            "item ref": "SS33",
          },
          {
            price: "1100e",
            size: "36x48",
            ordered: "20-Aug-2023",
            description: "Photograph",
            "item ref": "SS44",
          },
        ],
      },
      {
        linkables: [
          {
            "item ref": `/dashboard/items/batches/B07/Carpet/`,
          },
        ],
        Carpet: [
          {
            price: "300e",
            size: "5x8",
            ordered: "12-Jul-2023",
            description: "Area Rug",
            "item ref": "SS11",
          },
          {
            price: "450e",
            size: "8x10",
            ordered: "22-Jul-2023",
            description: "Runner Rug",
            "item ref": "SS22",
          },
          {
            price: "350e",
            size: "6x9",
            ordered: "05-Aug-2023",
            description: "Shag Carpet",
            "item ref": "SS33",
          },
          {
            price: "600e",
            size: "10x12",
            ordered: "15-Aug-2023",
            description: "Wool Rug",
            "item ref": "SS44",
          },
        ],
      },
    ],
  },
  {
    project: "MOR - Hall Pool",
    "project number": "MOR",
    "project name": "Hall Pool",
    "project manager": "Marcelo Ortega",
    "project status": "Active",
    "project type": "LOC",
    "start date": "04-feb-2023",
    linkables: [{ name: `/dashboard/items/batches/MOR/` }],
    "batch info": [
      {
        num: 1,
        name: "Sofas",
        type: "furniture",
      },
      {
        num: 2,
        name: "Tables",
        type: "furniture",
      },
      {
        num: 3,
        name: "Lighting",
        type: "decor",
      },
      {
        num: 4,
        name: "Rugs",
        type: "decor",
      },
    ],
    batches: [
      {
        Sofas: [
          {
            price: "1200e",
            description: "Sectional Sofa",
            "item ref": "SS01",
            supplier: "SOFCH",
            cur: "GBP",
          },
          {
            price: "800e",
            description: "Leather Sofa",
            "item ref": "SS02",
            supplier: "FURNCO",
            cur: "EUR",
          },
          {
            price: "600e",
            description: "Sleeper Sofa",
            "item ref": "SS03",
            supplier: "COMFYHOME",
            cur: "USD",
          },
          {
            price: "1000e",
            description: "Reclining Sofa",
            "item ref": "SS04",
            supplier: "MATTRESSPLUS",
            cur: "CAD",
          },
        ],
      },
      {
        Tables: [
          {
            price: "300e",
            description: "Coffee Table",
            "item ref": "TBL01",
            supplier: "HOMESTYLE",
            cur: "GBP",
          },
          {
            price: "250e",
            description: "End Table",
            "item ref": "TBL02",
            supplier: "FURNCO",
            cur: "EUR",
          },
          {
            price: "500e",
            description: "Console Table",
            "item ref": "TBL03",
            supplier: "WOODWORKS",
            cur: "USD",
          },
          {
            price: "400e",
            description: "Dining Table",
            "item ref": "TBL04",
            supplier: "CRAFTYFURNITURE",
            cur: "CAD",
          },
        ],
      },
      {
        Lighting: [
          {
            price: "150e",
            description: "Table Lamp",
            "item ref": "LMP01",
            supplier: "BRIGHTLIGHTS",
            cur: "GBP",
          },
          {
            price: "200e",
            description: "Floor Lamp",
            "item ref": "LMP02",
            supplier: "LIGHTINGDIRECT",
            cur: "EUR",
          },
          {
            price: "100e",
            description: "Pendant Light",
            "item ref": "LMP03",
            supplier: "LUMINAIRE",
            cur: "USD",
          },
          {
            price: "180e",
            description: "Wall Sconce",
            "item ref": "LMP04",
            supplier: "SHADESOFBRIGHT",
            cur: "CAD",
          },
        ],
      },
      {
        Rugs: [
          {
            price: "200e",
            description: "Area Rug",
            "item ref": "RUG01",
            supplier: "RUGGALLERY",
            cur: "GBP",
          },
          {
            price: "150e",
            description: "Runner Rug",
            "item ref": "RUG02",
            supplier: "FLOORCOVERINGS",
            cur: "EUR",
          },
          {
            price: "300e",
            description: "Shag Rug",
            "item ref": "RUG03",
            supplier: "PLUSHDECOR",
            cur: "USD",
          },
          {
            price: "250e",
            description: "Wool Rug",
            "item ref": "RUG04",
            supplier: "FINEFLOORINGS",
            cur: "CAD",
          },
        ],
      },
    ],
  },
  {
    project: "HID06 - Royal Garden",
    "project number": "HID06",
    "project name": "Royal Garden",
    "project manager": "Marcelo Ortega",
    "project status": "Active",
    "project type": "LOC",
    "start date": "04-nov-2023",
    linkables: [{ name: `/dashboard/items/batches/HID06/` }],
    "batch info": [
      { num: 1, name: "Living Room", type: "furniture" },
      { num: 2, name: "Dining Room", type: "furniture" },
      { num: 3, name: "Bedroom", type: "decor" },
      { num: 4, name: "Home Office", type: "decor" },
    ],
    batches: [
      {
        "Living Room": [
          {
            price: "1200e",
            size: "84x36x32",
            color: "Gray",
            material: "Fabric",
            description: "Sectional Sofa",
            "item ref": "SS01",
          },
          {
            price: "800e",
            size: "72x32x34",
            color: "Black",
            material: "Leather",
            description: "Reclining Sofa",
            "item ref": "SS02",
          },
          {
            price: "600e",
            size: "60x34x30",
            color: "Beige",
            material: "Fabric",
            description: "Sleeper Sofa",
            "item ref": "SS03",
          },
          {
            price: "1000e",
            size: "78x40x36",
            color: "Brown",
            material: "Leather",
            description: "Chesterfield Sofa",
            "item ref": "SS04",
          },
        ],
      },
      {
        "Dining Room": [
          {
            price: "500e",
            size: "72x36x30",
            color: "Oak",
            material: "Wood",
            description: "Dining Table",
            "item ref": "SS01",
          },
          {
            price: "350e",
            size: "48x30x30",
            color: "Walnut",
            material: "Wood",
            description: "Round Dining Table",
            "item ref": "SS02",
          },
          {
            price: "450e",
            size: "60x40x30",
            color: "Espresso",
            material: "Wood",
            description: "Rectangular Dining Table",
            "item ref": "SS03",
          },
          {
            price: "600e",
            size: "54x54x36",
            color: "Black",
            material: "Marble",
            description: "Marble Dining Table",
            "item ref": "SS04",
          },
        ],
      },
      {
        Bedroom: [
          {
            price: "800e",
            size: "60x80",
            color: "Gray",
            material: "Upholstered",
            description: "Platform Bed",
            "item ref": "SS01",
          },
          {
            price: "400e",
            size: "54x75",
            color: "White",
            material: "Wood",
            description: "Panel Bed",
            "item ref": "SS02",
          },
          {
            price: "600e",
            size: "78x82",
            color: "Beige",
            material: "Fabric",
            description: "Canopy Bed",
            "item ref": "SS03",
          },
          {
            price: "900e",
            size: "72x84",
            color: "Brown",
            material: "Leather",
            description: "Storage Bed",
            "item ref": "SS04",
          },
        ],
      },
      {
        "Home Office": [
          {
            price: "250e",
            size: "48x24x30",
            color: "White",
            material: "Wood",
            description: "Writing Desk",
            "item ref": "SS01",
          },
          {
            price: "200e",
            size: "60x30x30",
            color: "Black",
            material: "Metal",
            description: "Computer Desk",
            "item ref": "SS02",
          },
          {
            price: "300e",
            size: "72x36x30",
            color: "Espresso",
            material: "Wood",
            description: "Executive Desk",
            "item ref": "SS03",
          },
          {
            price: "400e",
            size: "54x20x30",
            color: "Brown",
            material: "Wood",
            description: "Console Desk",
            "item ref": "SS04",
          },
        ],
      },
    ],
  },
  {
    project: "C1180 - Golf Club",
    "project number": "C1180",
    "project name": "Golf Club",
    "project manager": "Bernardo Martos",
    "project status": "Active",
    "project type": "LOC",
    "start date": "04-sep-2023",
    linkables: [{ name: `/dashboard/items/batches/C1180/` }],
    "batch info": [
      { num: 1, name: "Sofas", type: "furniture" },
      { num: 2, name: "Tables", type: "furniture" },
      { num: 3, name: "Lighting", type: "decor" },
      { num: 4, name: "Rugs", type: "decor" },
    ],

    batches: [
      {
        Sofas: [
          {
            price: "1200e",
            size: "84x36x32",
            color: "Gray",
            material: "Fabric",
            description: "Sectional Sofa",
            "item ref": "SS01",
          },
          {
            price: "800e",
            size: "72x32x34",
            color: "Black",
            material: "Leather",
            description: "Leather Sofa",
            "item ref": "SS02",
          },
          {
            price: "600e",
            size: "60x34x30",
            color: "Beige",
            material: "Fabric",
            description: "Sleeper Sofa",
            "item ref": "SS03",
          },
          {
            price: "1000e",
            size: "78x40x36",
            color: "Brown",
            material: "Leather",
            description: "Reclining Sofa",
            "item ref": "SS04",
          },
        ],
      },
      {
        Tables: [
          {
            price: "300e",
            size: "60x30x18",
            color: "White",
            material: "Wood",
            description: "Coffee Table",
            "item ref": "SS01",
          },
          {
            price: "250e",
            size: "24x24x24",
            color: "Brown",
            material: "Wood",
            description: "End Table",
            "item ref": "SS02",
          },
          {
            price: "500e",
            size: "48x16x30",
            color: "Black",
            material: "Metal",
            description: "Console Table",
            "item ref": "SS03",
          },
          {
            price: "400e",
            size: "72x36x30",
            color: "Oak",
            material: "Wood",
            description: "Dining Table",
            "item ref": "SS04",
          },
        ],
      },
      {
        Lighting: [
          {
            price: "150e",
            size: "10x10x20",
            color: "Silver",
            material: "Metal",
            description: "Table Lamp",
            "item ref": "SS01",
          },
          {
            price: "200e",
            size: "12x12x60",
            color: "Black",
            material: "Metal",
            description: "Floor Lamp",
            "item ref": "SS02",
          },
          {
            price: "100e",
            size: "8x8x15",
            color: "Gold",
            material: "Glass",
            description: "Pendant Light",
            "item ref": "SS03",
          },
          {
            price: "180e",
            size: "6x6x10",
            color: "Bronze",
            material: "Metal",
            description: "Wall Sconce",
            "item ref": "SS04",
          },
        ],
      },
      {
        Rugs: [
          {
            price: "200e",
            size: "5x8",
            color: "Beige",
            material: "Wool",
            description: "Area Rug",
            "item ref": "SS01",
          },
          {
            price: "150e",
            size: "2x6",
            color: "Gray",
            material: "Cotton",
            description: "Runner Rug",
            "item ref": "SS02",
          },
          {
            price: "300e",
            size: "8x10",
            color: "Blue",
            material: "Polypropylene",
            description: "Shag Rug",
            "item ref": "SS03",
          },
          {
            price: "250e",
            size: "6x9",
            color: "Red",
            material: "Silk",
            description: "Wool Rug",
            "item ref": "SS04",
          },
        ],
      },
    ],
  },
];
